project:
  type: website
  output-dir: docs

website:
  title: "Bioinformatics - FISH 546"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus

      
      
  # sidebar:
  #   style: "docked"
  #   search: true
  #   contents:
  #     - section: "Syllabus"
  #       contents:
  #         - index.qmd
  
  
format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: visual

