project:
  type: website
  output-dir: docs

website:
  title: "Bioinformatics - FISH 546"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Syllabus"
        contents:
          - index.qmd
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

