---
title: "Syllabus"
---

## About

This course will teach core computing skills as well as project specific approaches. Each student will be developing and completing a research project targeting journal article submission by the end of the Quarter. There will be an emphasis on developing habits that increase automation which in turn will facilitate reproducibility. The course primary course platform will be centered around GitHub, with each student creating their own repositories.

T 3:00-4:20

Th 9:30-11:20

Location FSH 203

While you likely have perceptions of glamour in considering this course, a majority of time you spend in this discipline will be 1) moving files around, 2) googling code, and 3) installing software (in that order).

------------------------------------------------------------------------

Course[^1] GitHub Organization: <https://github.com/course-fish546-2023>

[^1]: https://github.com/sr320/course-fish546-2023

------------------------------------------------------------------------

## Repo List

| Name or UserID | course repo | project repo |
|----------------|-------------|--------------|
|                |             |              |
|                |             |              |
|                |             |              |

------------------------------------------------------------------------

## Textbook:

[Bioinformatics Data Skills](https://www.amazon.com/Bioinformatics-Data-Skills-Reproducible-Research/dp/1449367372/):

Reproducible and Robust Research with Open Source Tools By Vince Buffalo Publisher: O'Reilly Media Final Release Date: July 2015 Pages: 538

-   [The Supplementary Material Repository for Bioinformatics Data Skills](https://github.com/vsbuffalo/bds-files)

[\@uw](https://drive.google.com/a/uw.edu/file/d/0BwVK83sm6XQGWGNZUmlLckdZU1E/view?usp=sharing)

------------------------------------------------------------------------

## Grading

Each week there will be an assignment, you will need to made progress on your individual project, and complete a question set. You will give two presentations (Week 5; slides & Week 10 compendium). Question sets are based on a week's reading and material and is due by 3:00pm on Tuesday. Thus you will need to review the ["Topic" each week](schedule.qmd) before class (and before answering the question set.

| *Assignments*                    | Grade percentage | *comment*                 |
|----------------------------------|------------------|---------------------------|
| Weekly Question Set              | 25%              | due Tuesday at 3:00pm     |
| Weekly Class Assignment          | 35%              | due Friday at 5:00pm      |
| Weekly Research Project Progress | 20%              | assessed Friday at 5:00pm |
| Project Presentation             | 10%              | Week 5: slidedeck         |
| Project Completion               | 10%              | Week 10: compendium       |
