---
title: "Getting Started"
subtitle: "week 01"

format:
  html:
    code-fold: true
    code-tools: FALSE
    code-copy: true
    highlight-style: github
---

# Text Reading

How to Learn Bioinformatics 1-18;\
Setting Up and Managing a Bioinformatics Project 21-35;\
Remedial Unix Shell 37-54

# Expectations

# Setting up for Success!

As part of this class you will be learning fundamental skills in working with genomic data. In addition you will be carrying out an independent project throughout the quarter. Generally Tuesday will be learning a skillset and Thursday will be working on your independent project.

Each student will have two GitHub repositories, one where you complete "classwork" and as one devoted to your project. Both need to be in the organization `course-fish546-2023`.

The name of these repos:\
preferredname-*classwork* and\
preferredname-projectdescriptor

::: callout-important
Make sure you have you local repo clone in logical location (eg \~/Documents/GitHub) and that you do not move, nor place in Dropbox or similar syncing directory.
:::

Be sure to comply with guidelines

::: panel-tabset
## File Structure

-   Good file structure

    -   All project files in one main folder

    -   Subfolders (data, code, output)

-   Main folder is R project

    -   Self-contained project

    -   Use relative instead of absolute paths

-   Good folder & file names

    -   Descriptive but not too long

    -   No spaces

    -   Consistent format

## Data

-   Raw data

    -   In separate folder from cleaned data

    -   Never change!

    -   Each file should have metadata

## Code

-   Scripts with code

    -   Relative file paths to read in and create files

    -   Lots of comments

    -   Order: libraries, data, user-created functions, everything else

    -   Good variable & column names
:::

::: callout-warning
Max GitHub file size is 100MB
:::

There will be times when files are two big to include in repositories (or even you laptop). There will also be times when you have to run code outside of a GitHub repository. You will need to determine a way to effectively document this in your repository.

# Working in the command-line

Having already reviewed the prep material and completed the [bash tutorial](https://sr320.github.io/course-fish546-2023/assignments/00-bash.html) you are now ready to get to coding.

For the first task you will take an unknown multi-fasta file and annotate it using blast. You are welcome to do this in terminal, Rstudio, or jupyter. My recommendation, and how I will demonstrate is using Rmarkdown. Once you have have your project structured, we will download software, databases, a fasta file and run the code.

In your code directory create a file.

`01-blast.Rmd`

::: callout-tip
Rmarkdown is a good option as you can use markdown, add pictures and more!
:::

## Downloading software

NCBI Blast Software is at

<https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/>

::: callout-tip
It is best to decide on central location on computer where software will be downloaded.
:::

https://github.com/RobertsLab/code/blob/master/09-blast.ipynb

```bash
cd /Applications/bioinfo/
curl -O https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.13.0+-x64-macosx.tar.gz
tar -xf ncbi-blast-2.13.0+-x64-macosx.tar.gz

```

```bash
ls /Applications/bioinfo/

```

```bash
/Applications/bioinfo/ncbi-blast-2.13.0+/bin/blastx -h
```

## Make Blast Database

see <https://www.uniprot.org/downloads>

https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz

```bash
cd ../data
curl -O https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
mv uniprot_sprot.fasta.gz uniprot_sprot_r2023_01.fasta.gz
gunzip -k uniprot_sprot_r2023_01.fasta.gz
ls ../data
```
